### PR TITLE
empty placeholder issue.

### PR DESCRIPTION
**Pull request by rohanjariwala03**
Not showing editing lines when in edit mode with empty placeholder.

### CODE REVIEW

**Comment by rohanjariwala03** [comment]
Before 

Screenshot 2022-12-28 at 1 17 25 PM


After
Screenshot 2022-12-28 at 1 18 53 PM

**Comment by rohanjariwala03** [comment]
Any update for this PR?

**Comment by GRyabkin** [comment]
The PR fixes the issue as well https://github.com/Mehmetyaz/dashboard/issues/17

**Review by GRyabkin — APPROVED** [review]
Code works and fixes the issue https://github.com/Mehmetyaz/dashboard/issues/17

**Comment by GRyabkin** [comment]
@Mehmetyaz give some response/feedback please it would show that contributing to the project makes sense and it's not dead. I have plenty of requests that I could do myself and create pull requests on review.

**Comment by rohanjariwala03** [comment]
@GRyabkin Waiting since December still there is no response. I'm using it for production application. Hope he will reply soon.

**Comment by Mehmetyaz** [comment]
Hi @GRyabkin , @rohanjariwala03 . Sorry for late. In the past weeks, I couldn't take care of it due to the birth of my babies. I will make the project more lively as soon as possible.

**Review by Mehmetyaz — APPROVED** [review]

**Comment by GRyabkin** [comment]
@Mehmetyaz congratulations. Thank you for the merge.

**Pull request merged**
